<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.549">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Erika Carlson">
<meta name="dcterms.date" content="2023-03-25">

<title>exercise-11</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
</style>


<script src="exercise-11_files/libs/clipboard/clipboard.min.js"></script>
<script src="exercise-11_files/libs/quarto-html/quarto.js"></script>
<script src="exercise-11_files/libs/quarto-html/popper.min.js"></script>
<script src="exercise-11_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="exercise-11_files/libs/quarto-html/anchor.min.js"></script>
<link href="exercise-11_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="exercise-11_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="exercise-11_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="exercise-11_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="exercise-11_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">


</head>

<body class="fullcontent">

<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">

<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">exercise-11</h1>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Author</div>
    <div class="quarto-title-meta-contents">
             <p>Erika Carlson </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">March 25, 2023</p>
    </div>
  </div>
  
    
  </div>
  


</header>


<section id="exercise-11" class="level1 unnumbered">
<h1 class="unnumbered">Exercise 11</h1>
</section>
<section id="practice-anova" class="level1 unnumbered">
<h1 class="unnumbered">Practice ANOVA</h1>
<section id="preliminaries" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="preliminaries">Preliminaries</h4>
<blockquote class="blockquote">
<p><strong>Data source</strong>:</p>
<p>Tobias JA, et al.&nbsp;(2022). AVONET: Morphological, ecological and geographical data for all birds. <em>Ecology Letters</em> 25: 581–597.</p>
</blockquote>
<ul>
<li>Load in Morphological measurements on birds, AVONET data set
<ul>
<li>This is a recently published dataset that compiles morphological measurements and information on various ecological variables and geographic range data for more than 11,000 species of birds.</li>
</ul></li>
<li>Winnow the dataset to include only the following variables: <strong>Species1</strong>, <strong>Family1</strong>, <strong>Order1</strong>, <strong>Beak.Length_Culmen</strong>, <strong>Beak.Width</strong>, <strong>Beak.Depth</strong>, <strong>Tarsus.Length</strong>, <strong>Wing.Length</strong>, <strong>Tail.Length</strong>, <strong>Mass</strong>, <strong>Habitat</strong>, <strong>Migration</strong>, <strong>Trophic.Level</strong>, <strong>Trophic.Niche</strong>, <strong>Min.Latitude</strong>, <strong>Max.Latitude</strong>, <strong>Centroid.Latitude</strong>, <strong>Primary.Lifestyle</strong>, and <strong>Range.Size</strong></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(tidyverse)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(broom)</span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-4"><a href="#cb1-4" aria-hidden="true" tabindex="-1"></a>d <span class="ot">&lt;-</span> <span class="fu">read_csv</span>(<span class="st">"https://raw.githubusercontent.com/difiore/ada-2024-datasets/main/AVONETdataset1.csv"</span>, <span class="at">col_names =</span> <span class="cn">TRUE</span>)</span>
<span id="cb1-5"><a href="#cb1-5" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb1-6"><a href="#cb1-6" aria-hidden="true" tabindex="-1"></a><span class="co"># winnow data set</span></span>
<span id="cb1-7"><a href="#cb1-7" aria-hidden="true" tabindex="-1"></a>d <span class="ot">&lt;-</span> d <span class="sc">%&gt;%</span> <span class="fu">select</span>(Species1, Family1, Order1, Beak.Width, Beak.Depth, Tarsus.Length, Wing.Length, Tail.Length, Mass, Habitat, Migration, Trophic.Level, Trophic.Niche, Min.Latitude, Max.Latitude, Centroid.Latitude, Range.Size, Beak.Length_Culmen, Primary.Lifestyle)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ul>
<li>Run exploratory data analysis with this dataset and determine which variables are categorical and which are numeric.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb2"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb2-1"><a href="#cb2-1" aria-hidden="true" tabindex="-1"></a><span class="fu">glimpse</span>(d)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Rows: 11,009
Columns: 19
$ Species1           &lt;chr&gt; "Accipiter albogularis", "Accipiter badius", "Accip…
$ Family1            &lt;chr&gt; "Accipitridae", "Accipitridae", "Accipitridae", "Ac…
$ Order1             &lt;chr&gt; "Accipitriformes", "Accipitriformes", "Accipitrifor…
$ Beak.Width         &lt;dbl&gt; 10.6, 8.8, 8.6, 8.9, 8.7, 6.6, 8.3, 7.7, 8.6, 8.6, …
$ Beak.Depth         &lt;dbl&gt; 14.7, 11.6, 12.7, 11.9, 11.1, 12.0, 10.9, 9.6, 11.0…
$ Tarsus.Length      &lt;dbl&gt; 62.0, 43.0, 58.1, 61.2, 46.4, 48.7, 52.6, 60.3, 43.…
$ Wing.Length        &lt;dbl&gt; 235.2, 186.7, 229.6, 202.2, 217.6, 166.0, 163.5, 21…
$ Tail.Length        &lt;dbl&gt; 169.0, 140.6, 186.3, 140.8, 153.5, 127.0, 135.4, 15…
$ Mass               &lt;dbl&gt; 248.8, 131.2, 287.5, 142.0, 186.5, 122.0, 157.5, 16…
$ Habitat            &lt;chr&gt; "Forest", "Shrubland", "Woodland", "Forest", "Fores…
$ Migration          &lt;dbl&gt; 2, 3, 2, 2, 3, 1, 2, 2, 2, 3, 1, 1, 1, 1, 2, 1, 3, …
$ Trophic.Level      &lt;chr&gt; "Carnivore", "Carnivore", "Carnivore", "Carnivore",…
$ Trophic.Niche      &lt;chr&gt; "Vertivore", "Vertivore", "Vertivore", "Vertivore",…
$ Min.Latitude       &lt;dbl&gt; -11.73, -29.47, -55.72, -6.31, 31.19, 7.87, -10.36,…
$ Max.Latitude       &lt;dbl&gt; -4.02, 46.39, 23.73, -4.08, 55.86, 9.26, 10.12, 0.0…
$ Centroid.Latitude  &lt;dbl&gt; -8.15, 8.23, -10.10, -5.45, 45.24, 8.42, 0.71, -23.…
$ Range.Size         &lt;dbl&gt; 37461.21, 22374973.00, 14309701.27, 35580.71, 29367…
$ Beak.Length_Culmen &lt;dbl&gt; 27.7, 20.6, 25.0, 22.5, 21.1, 20.0, 20.5, 19.2, 20.…
$ Primary.Lifestyle  &lt;chr&gt; "Insessorial", "Insessorial", "Generalist", "Insess…</code></pre>
</div>
</div>
<ul>
<li><em>Species, Family, Order, Habitat are categorical and character</em></li>
<li><em>Migration is also categorical but numeric</em></li>
<li><em>All others are numeric</em></li>
</ul>
</section>
<section id="challenge-1" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="challenge-1">Challenge 1</h2>
<section id="one-factor-anova-and-inference" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="one-factor-anova-and-inference">One-Factor ANOVA and Inference</h3>
<section id="step-1" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="step-1">Step 1</h4>
<ul>
<li>Make boxplots of log(<strong>Mass</strong>) in relation to <strong>Trophic.Level</strong> and <strong>Migration</strong> behavior type. For each plot, drop from the visualization all species records where the categorical variable of interest is missing from the dataset. Also, convert the variable <strong>Migration</strong> (which is scored as a number: “1”, “2”, or “3”) from class numeric to either being classified as a factor or as a character (string) variable.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb4"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="co"># plot Mass as a factor of Trophic Level</span></span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>p1 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data =</span> d <span class="sc">%&gt;%</span> <span class="fu">drop_na</span>(Trophic.Level),</span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>             <span class="fu">aes</span>(<span class="at">x =</span> Trophic.Level, <span class="at">y =</span> <span class="fu">log</span>(Mass))) <span class="sc">+</span></span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span></span>
<span id="cb4-5"><a href="#cb4-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_jitter</span>(<span class="at">alpha =</span> <span class="fl">0.05</span>) <span class="sc">+</span></span>
<span id="cb4-6"><a href="#cb4-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"Trophic level"</span>)</span>
<span id="cb4-7"><a href="#cb4-7" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-8"><a href="#cb4-8" aria-hidden="true" tabindex="-1"></a><span class="co"># plot Mass as a factor of Migration (include argument as.factor())</span></span>
<span id="cb4-9"><a href="#cb4-9" aria-hidden="true" tabindex="-1"></a>p2 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data =</span> d <span class="sc">%&gt;%</span> <span class="fu">drop_na</span>(Migration),</span>
<span id="cb4-10"><a href="#cb4-10" aria-hidden="true" tabindex="-1"></a>             <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">as.factor</span>(Migration), <span class="at">y =</span> <span class="fu">log</span>(Mass))) <span class="sc">+</span></span>
<span id="cb4-11"><a href="#cb4-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span></span>
<span id="cb4-12"><a href="#cb4-12" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_jitter</span>(<span class="at">alpha =</span> <span class="fl">0.05</span>) <span class="sc">+</span></span>
<span id="cb4-13"><a href="#cb4-13" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"Migration"</span>)</span>
<span id="cb4-14"><a href="#cb4-14" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb4-15"><a href="#cb4-15" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggpubr)</span>
<span id="cb4-16"><a href="#cb4-16" aria-hidden="true" tabindex="-1"></a><span class="fu">ggarrange</span>(p1, p2,</span>
<span id="cb4-17"><a href="#cb4-17" aria-hidden="true" tabindex="-1"></a>          <span class="at">labels =</span> <span class="cn">NULL</span>,</span>
<span id="cb4-18"><a href="#cb4-18" aria-hidden="true" tabindex="-1"></a>          <span class="at">ncol =</span> <span class="dv">2</span>, <span class="at">nrow =</span> <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="exercise-11_files/figure-html/unnamed-chunk-3-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="step-2" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="step-2">Step 2</h4>
<ul>
<li>Run linear models using the <code>lm()</code> function to look at the relationship between log(<strong>Mass</strong>) and <strong>Trophic.Level</strong> and between log(<strong>Mass</strong>) and <strong>Migration</strong>.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1" aria-hidden="true" tabindex="-1"></a>m1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="fu">log</span>(Mass) <span class="sc">~</span> Trophic.Level, <span class="at">data =</span> d)</span>
<span id="cb5-2"><a href="#cb5-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb5-3"><a href="#cb5-3" aria-hidden="true" tabindex="-1"></a><span class="co"># need to coerce Migration as a factor before modeling</span></span>
<span id="cb5-4"><a href="#cb5-4" aria-hidden="true" tabindex="-1"></a>d <span class="ot">&lt;-</span> d <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(<span class="at">Migration =</span> <span class="fu">as.factor</span>(Migration))</span>
<span id="cb5-5"><a href="#cb5-5" aria-hidden="true" tabindex="-1"></a>m2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="fu">log</span>(Mass) <span class="sc">~</span> Migration, <span class="at">data =</span> d)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ul>
<li>Examine the output of the resultant linear models. Is log(<strong>Mass</strong>) associated with either <strong>Trophic.Level</strong> or <strong>Migration</strong> category? That is, in the global test of significance, is the F statistic large enough to reject the null hypothesis of an F value of zero?</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb6"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="co"># check beta coefficients</span></span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m1) <span class="co"># low p value for F statistic, very low adjusted R squared</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = log(Mass) ~ Trophic.Level, data = d)

Residuals:
    Min      1Q  Median      3Q     Max 
-3.4229 -1.1551 -0.3028  0.8982  7.5526 

Coefficients:
                       Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)             3.80834    0.01967 193.632  &lt; 2e-16 ***
Trophic.LevelHerbivore  0.25639    0.03406   7.528 5.54e-14 ***
Trophic.LevelOmnivore   0.01422    0.04116   0.345     0.73    
Trophic.LevelScavenger  4.63189    0.34447  13.446  &lt; 2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 1.538 on 11000 degrees of freedom
  (5 observations deleted due to missingness)
Multiple R-squared:  0.02094,   Adjusted R-squared:  0.02067 
F-statistic: 78.42 on 3 and 11000 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<div class="sourceCode cell-code" id="cb8"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Estimate tells us that for a change in trophic level from Carnivore (base) to Omnivore, there is a 25% increase in mean body mass</span></span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a><span class="co"># The coefficient for the intercept, i.e. beta_0 reflects the estimate of the mean value for Carnivores</span></span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = log(Mass) ~ Migration, data = d)

Residuals:
    Min      1Q  Median      3Q     Max 
-3.8924 -1.1769 -0.3088  0.9152  7.8427 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  3.77457    0.01636 230.710  &lt; 2e-16 ***
Migration2   0.75971    0.04731  16.059  &lt; 2e-16 ***
Migration3   0.37647    0.05155   7.303 3.02e-13 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 1.535 on 10983 degrees of freedom
  (23 observations deleted due to missingness)
Multiple R-squared:  0.02563,   Adjusted R-squared:  0.02546 
F-statistic: 144.5 on 2 and 10983 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<div class="sourceCode cell-code" id="cb10"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a><span class="co"># migration</span></span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="co"># sedentary = 1</span></span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a><span class="co"># partially migratory = 2</span></span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a><span class="co"># migratory = 3</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ul>
<li><em>Yes, log(Mass) is associated with both Trophic.Level and Migration, as both models have large F-statistics (78.42 and 144.5) and very low associated p-values (&lt; 2.2e-16 for both)</em></li>
<li>Given the regression coefficients returned for your <strong>Migration</strong> model, which <strong>Migration</strong> categor(ies) are different than the reference level? What level is the reference level?
<ul>
<li><em>Partially migratory and migratory are different than sedentary, level 1.</em></li>
</ul></li>
<li>Relevel and assess differences among the remaining pair of <strong>Migration</strong> categories.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb11"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb11-1"><a href="#cb11-1" aria-hidden="true" tabindex="-1"></a>m2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="fu">log</span>(Mass) <span class="sc">~</span> Migration, <span class="at">data =</span> d <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(<span class="at">Migration =</span> <span class="fu">relevel</span>(Migration, <span class="at">ref =</span> <span class="st">"3"</span>)))</span>
<span id="cb11-2"><a href="#cb11-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = log(Mass) ~ Migration, data = d %&gt;% mutate(Migration = relevel(Migration, 
    ref = "3")))

Residuals:
    Min      1Q  Median      3Q     Max 
-3.8924 -1.1769 -0.3088  0.9152  7.8427 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)  4.15104    0.04889  84.909  &lt; 2e-16 ***
Migration1  -0.37647    0.05155  -7.303 3.02e-13 ***
Migration2   0.38324    0.06603   5.804 6.67e-09 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 1.535 on 10983 degrees of freedom
  (23 observations deleted due to missingness)
Multiple R-squared:  0.02563,   Adjusted R-squared:  0.02546 
F-statistic: 144.5 on 2 and 10983 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<ul>
<li><em>Partially migratory and Migratory are also different</em></li>
<li>The coefficient for the intercept, beta_0, reflects the estimate of the mean log(Mass) for the first of our level variables</li>
<li>The estimate of beta_1 is the estimated difference in mean log(Mass) associated with being that level relative to the first (reference) level</li>
</ul>
</section>
<section id="step-3" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="step-3">Step 3</h4>
<ul>
<li>Conduct a post-hoc Tukey Honest Significant Differences test to also evaluate which <strong>Migration</strong> categories differ “significantly” from one another (see <a href="#module-20"><strong>Module 20</strong></a>).
<ul>
<li>After finding a significant omnibus F statistic in an ANOVA, we can test, post-hoc, what group means are different from on another using pairwise t-tests with an appropriate p value correction or a Tukey Honest Significant Differences test</li>
</ul></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb13"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb13-1"><a href="#cb13-1" aria-hidden="true" tabindex="-1"></a>m1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="fu">log</span>(Mass) <span class="sc">~</span> Trophic.Level, <span class="at">data =</span> d)</span>
<span id="cb13-2"><a href="#cb13-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb13-3"><a href="#cb13-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = log(Mass) ~ Trophic.Level, data = d)

Residuals:
    Min      1Q  Median      3Q     Max 
-3.4229 -1.1551 -0.3028  0.8982  7.5526 

Coefficients:
                       Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)             3.80834    0.01967 193.632  &lt; 2e-16 ***
Trophic.LevelHerbivore  0.25639    0.03406   7.528 5.54e-14 ***
Trophic.LevelOmnivore   0.01422    0.04116   0.345     0.73    
Trophic.LevelScavenger  4.63189    0.34447  13.446  &lt; 2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 1.538 on 11000 degrees of freedom
  (5 observations deleted due to missingness)
Multiple R-squared:  0.02094,   Adjusted R-squared:  0.02067 
F-statistic: 78.42 on 3 and 11000 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1" aria-hidden="true" tabindex="-1"></a><span class="co"># alternative way to run simple linear regression with `aov()`</span></span>
<span id="cb15-2"><a href="#cb15-2" aria-hidden="true" tabindex="-1"></a>m1aov <span class="ot">&lt;-</span> <span class="fu">aov</span>(<span class="fu">log</span>(Mass) <span class="sc">~</span> Trophic.Level, <span class="at">data =</span> d) </span>
<span id="cb15-3"><a href="#cb15-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb15-4"><a href="#cb15-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m1aov)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                 Df Sum Sq Mean Sq F value Pr(&gt;F)    
Trophic.Level     3    557  185.50   78.42 &lt;2e-16 ***
Residuals     11000  26020    2.37                   
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
5 observations deleted due to missingness</code></pre>
</div>
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Pairwise posthoc t-test</span></span>
<span id="cb17-2"><a href="#cb17-2" aria-hidden="true" tabindex="-1"></a>(<span class="fu">pairwise.t.test</span>(<span class="fu">log</span>(d<span class="sc">$</span>Mass), d<span class="sc">$</span>Trophic.Level, <span class="at">p.adj =</span> <span class="st">"bonferroni"</span>)) </span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pairwise comparisons using t tests with pooled SD 

data:  log(d$Mass) and d$Trophic.Level 

          Carnivore Herbivore Omnivore
Herbivore 3.3e-13   -         -       
Omnivore  1         6.7e-07   -       
Scavenger &lt; 2e-16   &lt; 2e-16   &lt; 2e-16 

P value adjustment method: bonferroni </code></pre>
</div>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Tukey test runs on aov object and is a comparable test, run slightly different</span></span>
<span id="cb19-2"><a href="#cb19-2" aria-hidden="true" tabindex="-1"></a>(posthoc <span class="ot">&lt;-</span> <span class="fu">TukeyHSD</span>(m1aov, <span class="at">which =</span> <span class="st">"Trophic.Level"</span>, <span class="at">conf.level =</span> <span class="fl">0.95</span>))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Tukey multiple comparisons of means
    95% family-wise confidence level

Fit: aov(formula = log(Mass) ~ Trophic.Level, data = d)

$Trophic.Level
                           diff         lwr        upr     p adj
Herbivore-Carnivore  0.25638774  0.16888205  0.3438934 0.0000000
Omnivore-Carnivore   0.01422185 -0.09154436  0.1199881 0.9858317
Scavenger-Carnivore  4.63188503  3.74679736  5.5169727 0.0000000
Omnivore-Herbivore  -0.24216589 -0.35936711 -0.1249647 0.0000007
Scavenger-Herbivore  4.37549729  3.48897045  5.2620241 0.0000000
Scavenger-Omnivore   4.61766318  3.72914808  5.5061783 0.0000000</code></pre>
</div>
</div>
</section>
<section id="step-4" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="step-4">Step 4</h4>
<ul>
<li>Use a permutation approach to inference to generate a null distribution of F statistic values for the model of log(<strong>Mass</strong>) in relation to <strong>Trophic.Level</strong> and calculate a p value for your original F statistic using the {infer} workflow and setting <code>calculate(stat="F")</code>.</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(infer)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: package 'infer' was built under R version 4.2.3</code></pre>
</div>
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1" aria-hidden="true" tabindex="-1"></a><span class="co"># calculate the original F statistic</span></span>
<span id="cb23-2"><a href="#cb23-2" aria-hidden="true" tabindex="-1"></a>original.F <span class="ot">&lt;-</span> <span class="fu">aov</span>(<span class="fu">log</span>(Mass) <span class="sc">~</span> Trophic.Level, <span class="at">data =</span> d) <span class="sc">%&gt;%</span> </span>
<span id="cb23-3"><a href="#cb23-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">tidy</span>() <span class="sc">%&gt;%</span> <span class="co"># pull table of coefficients from broom package</span></span>
<span id="cb23-4"><a href="#cb23-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">filter</span>(term <span class="sc">==</span> <span class="st">"Trophic.Level"</span>) <span class="co"># assign results of specific variable</span></span>
<span id="cb23-5"><a href="#cb23-5" aria-hidden="true" tabindex="-1"></a>original.F <span class="co"># results for F stat and p value for omnibus F test</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 6
  term             df sumsq meansq statistic  p.value
  &lt;chr&gt;         &lt;dbl&gt; &lt;dbl&gt;  &lt;dbl&gt;     &lt;dbl&gt;    &lt;dbl&gt;
1 Trophic.Level     3  557.   186.      78.4 3.43e-50</code></pre>
</div>
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a><span class="co"># generate a permutation distribution, breaking the association between predictor and response variable</span></span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a><span class="co"># generate a separate variable for log of body mass</span></span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a>d <span class="ot">&lt;-</span> d <span class="sc">%&gt;%</span> <span class="fu">mutate</span>(<span class="at">logMass =</span> <span class="fu">log</span>(Mass))</span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a>permuted.F <span class="ot">&lt;-</span> d <span class="sc">%&gt;%</span> </span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a>  <span class="fu">specify</span>(logMass <span class="sc">~</span> Trophic.Level) <span class="sc">%&gt;%</span> </span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a>  <span class="fu">hypothesize</span>(<span class="at">null =</span> <span class="st">"independence"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb25-8"><a href="#cb25-8" aria-hidden="true" tabindex="-1"></a>  <span class="fu">generate</span>(<span class="at">reps =</span> <span class="dv">1000</span>, <span class="at">type =</span> <span class="st">"permute"</span>) <span class="sc">%&gt;%</span> </span>
<span id="cb25-9"><a href="#cb25-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">calculate</span>(<span class="at">stat =</span> <span class="st">"F"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 5 rows containing missing values.</code></pre>
</div>
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a>permuted.F</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Response: logMass (numeric)
Explanatory: Trophic.Level (factor)
Null Hypothesis: independence
# A tibble: 1,000 × 2
   replicate  stat
       &lt;int&gt; &lt;dbl&gt;
 1         1 0.880
 2         2 1.26 
 3         3 2.45 
 4         4 1.04 
 5         5 0.616
 6         6 0.573
 7         7 0.107
 8         8 0.688
 9         9 0.496
10        10 0.827
# ℹ 990 more rows</code></pre>
</div>
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="fu">hist</span>(permuted.F<span class="sc">$</span>stat) <span class="co"># zero bounded, with decay (looks like an F distribution!)</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="exercise-11_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1" aria-hidden="true" tabindex="-1"></a><span class="fu">visualize</span>(permuted.F) <span class="sc">+</span></span>
<span id="cb30-2"><a href="#cb30-2" aria-hidden="true" tabindex="-1"></a>  <span class="fu">shade_p_value</span>(<span class="at">obs_stat =</span> original.F<span class="sc">$</span>statistic, </span>
<span id="cb30-3"><a href="#cb30-3" aria-hidden="true" tabindex="-1"></a>                <span class="at">direction =</span> <span class="st">"greater"</span>) <span class="co"># very far away from distribution because p value associated is very very tiny</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning in min(diff(unique_loc)): no non-missing arguments to min; returning
Inf</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="exercise-11_files/figure-html/unnamed-chunk-8-2.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Statistics is always comparing an observed test statistic to a distribution (whether a standardized distribution OR permuted distribution of test statistics from your data set)</p>
<ul>
<li>The number of times you generate a test statistic under null that the actual value of test statistic exceeds that permuted value</li>
<li>1000 permutations is usually good, maybe 10000</li>
</ul>
</section>
</section>
</section>
<section id="challenge-2" class="level2 unnumbered">
<h2 class="unnumbered anchored" data-anchor-id="challenge-2">Challenge 2</h2>
<section id="data-wrangling-one--and-two-factor-anova" class="level3 unnumbered">
<h3 class="unnumbered anchored" data-anchor-id="data-wrangling-one--and-two-factor-anova">Data Wrangling, One- and Two-Factor ANOVA</h3>
<section id="step-1-1" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="step-1-1">Step 1</h4>
<ul>
<li>Create the following two new variables and add them to AVONET dataset:
<ul>
<li><strong>Relative beak length</strong> = the <em>residual</em> of log(<strong>Beak.Length_Culmen</strong>) on log(<strong>Mass</strong>).</li>
<li><strong>Relative tarsus length</strong> = the <em>residual</em> of log(<strong>Tarsus.Length</strong>) on log(<strong>Mass</strong>).</li>
</ul></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb32"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb32-1"><a href="#cb32-1" aria-hidden="true" tabindex="-1"></a><span class="co"># failed strategy for pulling residuals</span></span>
<span id="cb32-2"><a href="#cb32-2" aria-hidden="true" tabindex="-1"></a><span class="co"># </span></span>
<span id="cb32-3"><a href="#cb32-3" aria-hidden="true" tabindex="-1"></a><span class="co"># m2 &lt;- lm(logMass ~ log(Beak.Length_Culmen), data = d)</span></span>
<span id="cb32-4"><a href="#cb32-4" aria-hidden="true" tabindex="-1"></a><span class="co"># </span></span>
<span id="cb32-5"><a href="#cb32-5" aria-hidden="true" tabindex="-1"></a><span class="co"># summary(m2)</span></span>
<span id="cb32-6"><a href="#cb32-6" aria-hidden="true" tabindex="-1"></a><span class="co"># </span></span>
<span id="cb32-7"><a href="#cb32-7" aria-hidden="true" tabindex="-1"></a><span class="co"># d &lt;- d %&gt;% mutate(relative_beak_length = m2$residuals)</span></span>
<span id="cb32-8"><a href="#cb32-8" aria-hidden="true" tabindex="-1"></a><span class="co"># </span></span>
<span id="cb32-9"><a href="#cb32-9" aria-hidden="true" tabindex="-1"></a><span class="co"># p &lt;- ggplot(data = d %&gt;% drop_na(Primary.Lifestyle), aes(x = Primary.Lifestyle, y = relative_beak_length)) + geom_boxplot() + theme(axis.text.x = element_text(angle = 90))</span></span>
<span id="cb32-10"><a href="#cb32-10" aria-hidden="true" tabindex="-1"></a><span class="co"># p</span></span>
<span id="cb32-11"><a href="#cb32-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-12"><a href="#cb32-12" aria-hidden="true" tabindex="-1"></a>d<span class="sc">$</span>relBL <span class="ot">&lt;-</span> <span class="fu">resid</span>(<span class="fu">lm</span>(<span class="at">formula =</span> <span class="fu">log</span>(Beak.Length_Culmen) <span class="sc">~</span> logMass, <span class="at">data =</span> d))</span>
<span id="cb32-13"><a href="#cb32-13" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb32-14"><a href="#cb32-14" aria-hidden="true" tabindex="-1"></a>d<span class="sc">$</span>relTL <span class="ot">&lt;-</span> <span class="fu">resid</span>(<span class="fu">lm</span>(<span class="at">formula =</span> <span class="fu">log</span>(Tarsus.Length) <span class="sc">~</span> logMass, <span class="at">data =</span> d))</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="step-2-1" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="step-2-1">Step 2</h4>
<ul>
<li>Make a boxplot of relative tarsus length variable in relation to <strong>Primary.Lifestyle</strong> and of relative beak length variable in relation to <strong>Trophic.Niche</strong></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb33"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a>p1 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data =</span> d <span class="sc">%&gt;%</span> <span class="fu">drop_na</span>(Primary.Lifestyle), </span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>             <span class="fu">aes</span>(<span class="at">x =</span> Primary.Lifestyle, <span class="at">y =</span> relTL)) <span class="sc">+</span> </span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span> </span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">90</span>)) <span class="sc">+</span></span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"Primary lifestyle"</span>) <span class="sc">+</span> <span class="fu">ylab</span>(<span class="st">"Relative tarsus length"</span>)</span>
<span id="cb33-6"><a href="#cb33-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-7"><a href="#cb33-7" aria-hidden="true" tabindex="-1"></a>p2 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data =</span> d <span class="sc">%&gt;%</span> <span class="fu">drop_na</span>(Trophic.Niche), </span>
<span id="cb33-8"><a href="#cb33-8" aria-hidden="true" tabindex="-1"></a>             <span class="fu">aes</span>(<span class="at">x =</span> Trophic.Niche, <span class="at">y =</span> relBL)) <span class="sc">+</span> </span>
<span id="cb33-9"><a href="#cb33-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span> </span>
<span id="cb33-10"><a href="#cb33-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">90</span>)) <span class="sc">+</span></span>
<span id="cb33-11"><a href="#cb33-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"Trophic niche"</span>) <span class="sc">+</span> <span class="fu">ylab</span>(<span class="st">"Relative beak length"</span>)</span>
<span id="cb33-12"><a href="#cb33-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb33-13"><a href="#cb33-13" aria-hidden="true" tabindex="-1"></a><span class="fu">ggarrange</span>(p1, p2,</span>
<span id="cb33-14"><a href="#cb33-14" aria-hidden="true" tabindex="-1"></a>          <span class="at">labels =</span> <span class="cn">NULL</span>,</span>
<span id="cb33-15"><a href="#cb33-15" aria-hidden="true" tabindex="-1"></a>          <span class="at">ncol =</span> <span class="dv">2</span>, <span class="at">nrow =</span> <span class="dv">1</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="exercise-11_files/figure-html/unnamed-chunk-10-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="step-3-1" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="step-3-1">Step 3</h4>
<ul>
<li>Run an ANOVA analyses to look at the association between geographic range size and the variable <strong>Migration</strong>
<ul>
<li>Drop those observations for which <strong>Migration</strong> is not scored</li>
<li>Look at the distribution of the variable <strong>Range.Size</strong> to decide whether and how it might need to be transformed (log)</li>
<li>Based on the global model, is range size associated with form of migration? <em>Yes</em></li>
<li>How much of the variance in your measure of range size is associated with <strong>Migration</strong> behavior style? <em>Adjusted r-squared = 0.08674, so 8.7% of the variance</em></li>
</ul></li>
<li>Given the regression coefficients returned in output of the model, which <strong>Migration</strong> categor(ies) are different than the reference level? What level is the reference level? Relevel and assess differences among the remaining pair of <strong>Migration</strong> categories. Also conduct a post-hoc Tukey Honest Significant Differences test to also evaluate which <strong>Migration</strong> categories differ “significantly” from one another (see <a href="#module-20"><strong>Module 20</strong></a>).</li>
</ul>
<p>Run an ANOVA on geographic range as a function of migratory status</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb34"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb34-1"><a href="#cb34-1" aria-hidden="true" tabindex="-1"></a>m1aov <span class="ot">&lt;-</span> <span class="fu">aov</span>(<span class="fu">log</span>(Range.Size) <span class="sc">~</span> Migration, <span class="at">data =</span> d <span class="sc">%&gt;%</span> <span class="fu">drop_na</span>(Migration)) </span>
<span id="cb34-2"><a href="#cb34-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m1aov)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>               Df Sum Sq Mean Sq F value Pr(&gt;F)    
Migration       2   8071    4035   520.3 &lt;2e-16 ***
Residuals   10934  84798       8                   
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1
49 observations deleted due to missingness</code></pre>
</div>
<div class="sourceCode cell-code" id="cb36"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb36-1"><a href="#cb36-1" aria-hidden="true" tabindex="-1"></a><span class="fu">TukeyHSD</span>(m1aov)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>  Tukey multiple comparisons of means
    95% family-wise confidence level

Fit: aov(formula = log(Range.Size) ~ Migration, data = d %&gt;% drop_na(Migration))

$Migration
         diff      lwr      upr p adj
2-1 1.7846901 1.582952 1.986428     0
3-1 2.5170168 2.297150 2.736883     0
3-2 0.7323266 0.450689 1.013964     0</code></pre>
</div>
<div class="sourceCode cell-code" id="cb38"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb38-1"><a href="#cb38-1" aria-hidden="true" tabindex="-1"></a><span class="fu">ggplot</span>(d <span class="sc">%&gt;%</span> <span class="fu">drop_na</span>(Migration), </span>
<span id="cb38-2"><a href="#cb38-2" aria-hidden="true" tabindex="-1"></a>       <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">as.factor</span>(Migration), <span class="at">y =</span> <span class="fu">log</span>(Range.Size))) <span class="sc">+</span></span>
<span id="cb38-3"><a href="#cb38-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span></span>
<span id="cb38-4"><a href="#cb38-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_jitter</span>(<span class="at">alpha =</span> <span class="fl">0.05</span>) <span class="sc">+</span></span>
<span id="cb38-5"><a href="#cb38-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"Migration"</span>) <span class="sc">+</span> <span class="fu">ylab</span>(<span class="st">"log(Range size)"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 49 rows containing non-finite values (`stat_boxplot()`).</code></pre>
</div>
<div class="cell-output cell-output-stderr">
<pre><code>Warning: Removed 49 rows containing missing values (`geom_point()`).</code></pre>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="exercise-11_files/figure-html/unnamed-chunk-11-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="cb41"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="co"># get the R-squared of the anova by looking at the summary output of the corresponding linear model</span></span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a>m1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="fu">log</span>(Range.Size) <span class="sc">~</span> Migration, <span class="at">data =</span> d <span class="sc">%&gt;%</span> <span class="fu">drop_na</span>(Migration))</span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a><span class="fu">anova</span>(m1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Analysis of Variance Table

Response: log(Range.Size)
             Df Sum Sq Mean Sq F value    Pr(&gt;F)    
Migration     2   8071  4035.3  520.32 &lt; 2.2e-16 ***
Residuals 10934  84798     7.8                      
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
<div class="sourceCode cell-code" id="cb43"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb43-1"><a href="#cb43-1" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = log(Range.Size) ~ Migration, data = d %&gt;% drop_na(Migration))

Residuals:
     Min       1Q   Median       3Q      Max 
-14.5710  -1.4521   0.4357   1.9763   5.9271 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 12.03381    0.02974  404.62   &lt;2e-16 ***
Migration2   1.78469    0.08606   20.74   &lt;2e-16 ***
Migration3   2.51702    0.09380   26.83   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 2.785 on 10934 degrees of freedom
  (49 observations deleted due to missingness)
Multiple R-squared:  0.0869,    Adjusted R-squared:  0.08674 
F-statistic: 520.3 on 2 and 10934 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
</section>
<section id="step-4-1" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="step-4-1">Step 4</h4>
<ul>
<li>Winnow the data to just consider birds from the Infraorder “Passeriformes” (song birds).</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb45"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb45-1"><a href="#cb45-1" aria-hidden="true" tabindex="-1"></a>d_pass <span class="ot">&lt;-</span> d <span class="sc">%&gt;%</span> <span class="fu">filter</span>(Order1 <span class="sc">==</span> <span class="st">"Passeriformes"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
<ul>
<li>Run separate one-factor ANOVA analyses to look at the association between [1] relative beak length and <strong>Primary.Lifestyle</strong> and between [2] relative beak length and <strong>Trophic.Level</strong>.
<ul>
<li>Make boxplots of response variable by each predictor and by the combination of predictors.</li>
<li>Run linear models for each predictor separately and interpret the model output.</li>
<li><em>Primary lifestyle and trophic level significantly effect relative beak length when modeled separately, based on large F values and very small p-value associated with each global model</em></li>
</ul></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb46"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb46-1"><a href="#cb46-1" aria-hidden="true" tabindex="-1"></a>m0aov <span class="ot">&lt;-</span> <span class="fu">aov</span>(relBL <span class="sc">~</span> <span class="dv">1</span>, <span class="at">data =</span> d_pass)</span>
<span id="cb46-2"><a href="#cb46-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb46-3"><a href="#cb46-3" aria-hidden="true" tabindex="-1"></a>m1aov <span class="ot">&lt;-</span> <span class="fu">aov</span>(relBL <span class="sc">~</span> Primary.Lifestyle, <span class="at">data =</span> d_pass)</span>
<span id="cb46-4"><a href="#cb46-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m1aov)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                    Df Sum Sq Mean Sq F value Pr(&gt;F)    
Primary.Lifestyle    3   18.2   6.067   130.2 &lt;2e-16 ***
Residuals         6610  307.9   0.047                   
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
<div class="sourceCode cell-code" id="cb48"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb48-1"><a href="#cb48-1" aria-hidden="true" tabindex="-1"></a>m2aov <span class="ot">&lt;-</span> <span class="fu">aov</span>(relBL <span class="sc">~</span> Trophic.Level, <span class="at">data =</span> d_pass)</span>
<span id="cb48-2"><a href="#cb48-2" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m2aov)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                Df Sum Sq Mean Sq F value Pr(&gt;F)    
Trophic.Level    2  16.31   8.154     174 &lt;2e-16 ***
Residuals     6611 309.81   0.047                   
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
<div class="sourceCode cell-code" id="cb50"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb50-1"><a href="#cb50-1" aria-hidden="true" tabindex="-1"></a>p1 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data =</span> d_pass <span class="sc">%&gt;%</span> <span class="fu">drop_na</span>(Primary.Lifestyle), </span>
<span id="cb50-2"><a href="#cb50-2" aria-hidden="true" tabindex="-1"></a>             <span class="fu">aes</span>(<span class="at">x =</span> Primary.Lifestyle, <span class="at">y =</span> relBL)) <span class="sc">+</span> </span>
<span id="cb50-3"><a href="#cb50-3" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span> </span>
<span id="cb50-4"><a href="#cb50-4" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_jitter</span>(<span class="at">alpha =</span> <span class="fl">0.025</span>) <span class="sc">+</span></span>
<span id="cb50-5"><a href="#cb50-5" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"Primary lifestyle"</span>) <span class="sc">+</span> <span class="fu">ylab</span>(<span class="st">"Relative beak length"</span>)</span>
<span id="cb50-6"><a href="#cb50-6" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb50-7"><a href="#cb50-7" aria-hidden="true" tabindex="-1"></a>p2 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data =</span> d_pass <span class="sc">%&gt;%</span> <span class="fu">drop_na</span>(Trophic.Level), </span>
<span id="cb50-8"><a href="#cb50-8" aria-hidden="true" tabindex="-1"></a>             <span class="fu">aes</span>(<span class="at">x =</span> Trophic.Level, <span class="at">y =</span> relBL)) <span class="sc">+</span> </span>
<span id="cb50-9"><a href="#cb50-9" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span> </span>
<span id="cb50-10"><a href="#cb50-10" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_jitter</span>(<span class="at">alpha =</span> <span class="fl">0.025</span>) <span class="sc">+</span></span>
<span id="cb50-11"><a href="#cb50-11" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"Trophic level"</span>) <span class="sc">+</span> <span class="fu">ylab</span>(<span class="st">"Relative beak length"</span>)</span>
<span id="cb50-12"><a href="#cb50-12" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb50-13"><a href="#cb50-13" aria-hidden="true" tabindex="-1"></a><span class="co"># combination</span></span>
<span id="cb50-14"><a href="#cb50-14" aria-hidden="true" tabindex="-1"></a>p3 <span class="ot">&lt;-</span> <span class="fu">ggplot</span>(<span class="at">data =</span> d_pass <span class="sc">%&gt;%</span> <span class="fu">drop_na</span>(Primary.Lifestyle), </span>
<span id="cb50-15"><a href="#cb50-15" aria-hidden="true" tabindex="-1"></a>             <span class="fu">aes</span>(<span class="at">x =</span> Primary.Lifestyle, <span class="at">y =</span> relBL)) <span class="sc">+</span> </span>
<span id="cb50-16"><a href="#cb50-16" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_boxplot</span>() <span class="sc">+</span> </span>
<span id="cb50-17"><a href="#cb50-17" aria-hidden="true" tabindex="-1"></a>  <span class="fu">facet_wrap</span>(<span class="sc">~</span> Trophic.Level) <span class="sc">+</span></span>
<span id="cb50-18"><a href="#cb50-18" aria-hidden="true" tabindex="-1"></a>  <span class="fu">geom_jitter</span>(<span class="at">alpha =</span> <span class="fl">0.025</span>) <span class="sc">+</span></span>
<span id="cb50-19"><a href="#cb50-19" aria-hidden="true" tabindex="-1"></a>  <span class="fu">theme</span>(<span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">90</span>)) <span class="sc">+</span></span>
<span id="cb50-20"><a href="#cb50-20" aria-hidden="true" tabindex="-1"></a>  <span class="fu">xlab</span>(<span class="st">"Primary lifestyle"</span>) <span class="sc">+</span> <span class="fu">ylab</span>(<span class="st">"Relative beak length"</span>)</span>
<span id="cb50-21"><a href="#cb50-21" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb50-22"><a href="#cb50-22" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(ggpubr)</span>
<span id="cb50-23"><a href="#cb50-23" aria-hidden="true" tabindex="-1"></a><span class="fu">ggarrange</span>(p1, p2, p3,</span>
<span id="cb50-24"><a href="#cb50-24" aria-hidden="true" tabindex="-1"></a>          <span class="at">labels =</span> <span class="cn">NULL</span>,</span>
<span id="cb50-25"><a href="#cb50-25" aria-hidden="true" tabindex="-1"></a>          <span class="at">ncol =</span> <span class="dv">2</span>, <span class="at">nrow =</span> <span class="dv">2</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="exercise-11_files/figure-html/unnamed-chunk-13-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="step-5" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="step-5">Step 5</h4>
<ul>
<li>Run a two-factor model to look at the association between relative beak length and both <strong>Primary.Lifestyle</strong> and <strong>Trophic.Level</strong> among the passeriforms.</li>
<li>Based on the model output, what would you conclude about how relative beak length is related to these two variables? <em>Both Trophic.Level and Primary.Lifestyle are predictive of relative beak length, and this combination accounts for 10.9% of the variance in relative beak length</em></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb51"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb51-1"><a href="#cb51-1" aria-hidden="true" tabindex="-1"></a>m1aov2 <span class="ot">&lt;-</span> <span class="fu">aov</span>(relBL <span class="sc">~</span> Trophic.Level <span class="sc">+</span> Primary.Lifestyle, </span>
<span id="cb51-2"><a href="#cb51-2" aria-hidden="true" tabindex="-1"></a>              <span class="at">data =</span> d_pass)</span>
<span id="cb51-3"><a href="#cb51-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m1aov2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                    Df Sum Sq Mean Sq F value Pr(&gt;F)    
Trophic.Level        2  16.31   8.154   185.7 &lt;2e-16 ***
Primary.Lifestyle    3  19.57   6.523   148.5 &lt;2e-16 ***
Residuals         6608 290.24   0.044                   
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
<div class="sourceCode cell-code" id="cb53"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb53-1"><a href="#cb53-1" aria-hidden="true" tabindex="-1"></a><span class="co"># get the R-squared of the anova by looking at the summary output of the corresponding linear model</span></span>
<span id="cb53-2"><a href="#cb53-2" aria-hidden="true" tabindex="-1"></a>m1 <span class="ot">&lt;-</span> <span class="fu">lm</span>(relBL <span class="sc">~</span> Trophic.Level <span class="sc">+</span> Primary.Lifestyle, </span>
<span id="cb53-3"><a href="#cb53-3" aria-hidden="true" tabindex="-1"></a>              <span class="at">data =</span> d_pass)</span>
<span id="cb53-4"><a href="#cb53-4" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m1)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = relBL ~ Trophic.Level + Primary.Lifestyle, data = d_pass)

Residuals:
     Min       1Q   Median       3Q      Max 
-0.65365 -0.13329 -0.02284  0.10274  1.20180 

Coefficients:
                              Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept)                  -0.349502   0.020958 -16.677   &lt;2e-16 ***
Trophic.LevelHerbivore       -0.126397   0.006761 -18.695   &lt;2e-16 ***
Trophic.LevelOmnivore         0.012140   0.006450   1.882   0.0599 .  
Primary.LifestyleGeneralist   0.301517   0.022582  13.352   &lt;2e-16 ***
Primary.LifestyleInsessorial  0.375698   0.021295  17.642   &lt;2e-16 ***
Primary.LifestyleTerrestrial  0.302119   0.021942  13.769   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.2096 on 6608 degrees of freedom
Multiple R-squared:   0.11, Adjusted R-squared:  0.1093 
F-statistic: 163.4 on 5 and 6608 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
</section>
<section id="step-6" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="step-6">Step 6</h4>
<ul>
<li>Finally, run an additional two-way model with the same dataset and predictors, but adding the possibility of an interaction term using the colon operator (<code>:</code>)
<ul>
<li>e.g., relative beak length ~ <strong>Primary.Lifestyle</strong> + <strong>Trophic.Level</strong> + <strong>Primary.Lifestyle:Trophic.Level</strong>.</li>
<li>Based on the model output, what would you now conclude about how relative beak length is related to these two variables? <em>Both Trophic.Level and Primary.Lifestyle are predictive of relative beak length, as is the interaction between these two predictors, all accounting for 13.5% of the variance in beak length</em></li>
</ul></li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb55"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb55-1"><a href="#cb55-1" aria-hidden="true" tabindex="-1"></a>m2aov2 <span class="ot">&lt;-</span> <span class="fu">aov</span>(relBL <span class="sc">~</span> Trophic.Level <span class="sc">+</span> Primary.Lifestyle <span class="sc">+</span> Trophic.Level<span class="sc">:</span>Primary.Lifestyle, </span>
<span id="cb55-2"><a href="#cb55-2" aria-hidden="true" tabindex="-1"></a>              <span class="at">data =</span> d_pass)</span>
<span id="cb55-3"><a href="#cb55-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m2aov2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                                  Df Sum Sq Mean Sq F value Pr(&gt;F)    
Trophic.Level                      2  16.31   8.154  191.08 &lt;2e-16 ***
Primary.Lifestyle                  3  19.57   6.523  152.84 &lt;2e-16 ***
Trophic.Level:Primary.Lifestyle    4   8.41   2.102   49.26 &lt;2e-16 ***
Residuals                       6604 281.83   0.043                   
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1</code></pre>
</div>
<div class="sourceCode cell-code" id="cb57"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb57-1"><a href="#cb57-1" aria-hidden="true" tabindex="-1"></a>m2 <span class="ot">&lt;-</span> <span class="fu">lm</span>(relBL <span class="sc">~</span> Trophic.Level <span class="sc">+</span> Primary.Lifestyle <span class="sc">+</span> Trophic.Level<span class="sc">:</span>Primary.Lifestyle, </span>
<span id="cb57-2"><a href="#cb57-2" aria-hidden="true" tabindex="-1"></a>              <span class="at">data =</span> d_pass)</span>
<span id="cb57-3"><a href="#cb57-3" aria-hidden="true" tabindex="-1"></a><span class="fu">summary</span>(m2)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = relBL ~ Trophic.Level + Primary.Lifestyle + Trophic.Level:Primary.Lifestyle, 
    data = d_pass)

Residuals:
     Min       1Q   Median       3Q      Max 
-0.64623 -0.12836 -0.02078  0.10070  1.21924 

Coefficients: (2 not defined because of singularities)
                                                    Estimate Std. Error t value
(Intercept)                                         -0.34950    0.02066 -16.918
Trophic.LevelHerbivore                              -0.27502    0.01562 -17.608
Trophic.LevelOmnivore                               -0.11080    0.01550  -7.150
Primary.LifestyleGeneralist                          0.33010    0.02367  13.948
Primary.LifestyleInsessorial                         0.35826    0.02104  17.031
Primary.LifestyleTerrestrial                         0.35714    0.02210  16.162
Trophic.LevelHerbivore:Primary.LifestyleGeneralist   0.05033    0.02584   1.948
Trophic.LevelOmnivore:Primary.LifestyleGeneralist    0.09898    0.02351   4.210
Trophic.LevelHerbivore:Primary.LifestyleInsessorial  0.20115    0.01750  11.494
Trophic.LevelOmnivore:Primary.LifestyleInsessorial   0.15527    0.01726   8.996
Trophic.LevelHerbivore:Primary.LifestyleTerrestrial       NA         NA      NA
Trophic.LevelOmnivore:Primary.LifestyleTerrestrial        NA         NA      NA
                                                    Pr(&gt;|t|)    
(Intercept)                                          &lt; 2e-16 ***
Trophic.LevelHerbivore                               &lt; 2e-16 ***
Trophic.LevelOmnivore                               9.61e-13 ***
Primary.LifestyleGeneralist                          &lt; 2e-16 ***
Primary.LifestyleInsessorial                         &lt; 2e-16 ***
Primary.LifestyleTerrestrial                         &lt; 2e-16 ***
Trophic.LevelHerbivore:Primary.LifestyleGeneralist    0.0515 .  
Trophic.LevelOmnivore:Primary.LifestyleGeneralist   2.59e-05 ***
Trophic.LevelHerbivore:Primary.LifestyleInsessorial  &lt; 2e-16 ***
Trophic.LevelOmnivore:Primary.LifestyleInsessorial   &lt; 2e-16 ***
Trophic.LevelHerbivore:Primary.LifestyleTerrestrial       NA    
Trophic.LevelOmnivore:Primary.LifestyleTerrestrial        NA    
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 0.2066 on 6604 degrees of freedom
Multiple R-squared:  0.1358,    Adjusted R-squared:  0.1346 
F-statistic: 115.3 on 9 and 6604 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="cb59"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb59-1"><a href="#cb59-1" aria-hidden="true" tabindex="-1"></a><span class="co"># can do more variables using *</span></span>
<span id="cb59-2"><a href="#cb59-2" aria-hidden="true" tabindex="-1"></a>m1aov3 <span class="ot">&lt;-</span> <span class="fu">aov</span>(relBL <span class="sc">~</span> Trophic.Level <span class="sc">*</span> Primary.Lifestyle <span class="sc">*</span> <span class="fu">as.factor</span>(Migration), </span>
<span id="cb59-3"><a href="#cb59-3" aria-hidden="true" tabindex="-1"></a>              <span class="at">data =</span> d_pass)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
<section id="step-7" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="step-7">Step 7</h4>
<ul>
<li>Use the <code>interaction.plot()</code> function to visualize the interaction between <strong>Primary.Lifestyle</strong> and <strong>Trophic.Level</strong> (see <a href="#module-20"><strong>Module 20</strong></a>).</li>
</ul>
<div class="cell">
<div class="sourceCode cell-code" id="cb60"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb60-1"><a href="#cb60-1" aria-hidden="true" tabindex="-1"></a><span class="fu">interaction.plot</span>(</span>
<span id="cb60-2"><a href="#cb60-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">x.factor =</span> d_pass<span class="sc">$</span>Trophic.Level,</span>
<span id="cb60-3"><a href="#cb60-3" aria-hidden="true" tabindex="-1"></a>  <span class="at">xlab =</span> <span class="st">"Trophic level"</span>,</span>
<span id="cb60-4"><a href="#cb60-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">trace.factor =</span> d_pass<span class="sc">$</span>Primary.Lifestyle,</span>
<span id="cb60-5"><a href="#cb60-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">trace.label =</span> <span class="st">"Primary lifestyle"</span>,</span>
<span id="cb60-6"><a href="#cb60-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">response =</span> d_pass<span class="sc">$</span>relBL,</span>
<span id="cb60-7"><a href="#cb60-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">ylab =</span> <span class="st">"Mean relative beak length"</span></span>
<span id="cb60-8"><a href="#cb60-8" aria-hidden="true" tabindex="-1"></a>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="exercise-11_files/figure-html/unnamed-chunk-17-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="additional-steps" class="level4 unnumbered">
<h4 class="unnumbered anchored" data-anchor-id="additional-steps">Additional Steps?</h4>
<p>(in progress)</p>
<p>In the exercise above, we really did not do any checking with this dataset to see if the data meet the primary assumptions for standard linear regression and ANOVA, which are that variables/residuals within each grouping level are roughly normally distributed and have roughly equal variances. Sample sizes within each grouping level should also be roughly equal. As noted in <a href="#module-20"><strong>Module 20</strong></a>, a general rule of thumb for “equal” variances is to compare the largest and smallest within-grouping level standard deviations and, if this value is less than 2, then it is often reasonable to presume the assumption may not be violated.</p>
<p>Use this approach to see whether variances in across groups in your various models (e.g., for relative beak length ~ trophic level) are roughly equal. Additionally, do a visual check of whether observations and model residuals within groups look to be normally distributed.</p>
<ul>
<li>Check residual analysis by eye</li>
</ul>
<p>Looking for a nice scatter of points around a horizontal line (should be no relationship)</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb61"><pre class="sourceCode r code-with-copy"><code class="sourceCode r"><span id="cb61-1"><a href="#cb61-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(car)</span>
<span id="cb61-2"><a href="#cb61-2" aria-hidden="true" tabindex="-1"></a><span class="fu">install.packages</span>(<span class="st">"jtools"</span>)</span>
<span id="cb61-3"><a href="#cb61-3" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(jtools)</span>
<span id="cb61-4"><a href="#cb61-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb61-5"><a href="#cb61-5" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(m1<span class="sc">$</span>model<span class="sc">$</span>Trophic.Level, <span class="fu">residuals</span>(m1))</span>
<span id="cb61-6"><a href="#cb61-6" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(m1<span class="sc">$</span>model<span class="sc">$</span>Primary.Lifestyle, <span class="fu">residuals</span>(m1))</span>
<span id="cb61-7"><a href="#cb61-7" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(<span class="fu">fitted</span>(m1), <span class="fu">residuals</span>(m1)) <span class="co"># plotting residuals given combinations of Trophic.Level and Primary.Lifestyle</span></span>
<span id="cb61-8"><a href="#cb61-8" aria-hidden="true" tabindex="-1"></a><span class="fu">plot</span>(m1) <span class="co"># opens interactive plot window</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</div>
</section>
</section>
</section>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>